FROM nvidia/cuda:13.0.0-cudnn-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

WORKDIR /FastVideo

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget git ca-certificates openssh-server zsh vim curl \
    gcc-11 g++-11 clang-11 build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-11

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=${CUDA_HOME}/bin:${PATH}
ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}

# uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    echo 'source $HOME/.local/bin/env' >> /root/.bashrc

COPY pyproject.toml ./
RUN echo "# Placeholder" > README.md

# Python env
RUN source $HOME/.local/bin/env && \
    uv venv --python 3.12 --seed /opt/venv && \
    source /opt/venv/bin/activate && \
    uv pip install --upgrade pip && \
    uv pip install torch==2.11.0 torchvision==0.26.0 torchaudio==2.11.0

COPY . .

RUN source $HOME/.local/bin/env && \
    source /opt/venv/bin/activate && \
    uv pip install -e .[dev] && \
    echo 'source /opt/venv/bin/activate' >> /root/.bashrc

# 不装 FA
# 不 build kernel

CMD ["/bin/bash"]